qcar2_behavior_tree_manager:
  ros__parameters:
    tick_hz: 5.0
    require_tf: true # Set to true when SLAM/localization is running
    goal_reached_distance: 0.2
    goal_timeout_sec: 999.0
    goal_frame_id: pgm_map

    goal_output_topic: /bt/goal #cambiar al nuevo topico
    state_output_topic: /bt/state
    mode_output_topic: /bt/mode_hybrid
    mode_numeric_output_topic: /bt/mode_hybrid_numeric
    default_mode_hybrid: HYBRID

    mode_code_stop: 0.0
    mode_code_hybrid: 1.0
    mode_code_pid: 2.0

    goal_1: [4.577, 1.558, 0.7, 0.7]
    goal_2: [4.5473, 4.4822, 0.7, 0.7]
    goal_3: [2.67, 5.93, 1.0, 0.0]
    goal_4: [1.41, 2.25, 0.0, 1.0]
    goal_5: [4.6, 3.2, 0.7, 0.7]
    goal_6: [1.14, 0.52, -0.31, 0.94]

    additional_goals: []

    mission_loop:
      - set_mode:HYBRID
      - set_led:init
      - wait:60.0
      - set_led:to_pickup
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - wait:5.0
      - set_led:pickup_done
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - set_led:dropoff_done
      - wait:5.0
      - set_led:dropoff_done
      - dispatch_next_goal
      - wait_goal_reached_or_timeout
      - set_led:dropoff_done
      - dispatch_next_goal
      - wait_goal_reached_or_timeout


      - set_led:idle
      - wait:17.0
      - set_led:idle
      - set_mode:STOPPED
